### ISSUE TITLE
Update app icon

### ISSUE THREAD

**Issue by joe-mcguinness** [PlasticPatrol/PlasticPatrolWeb#19] opened 2020-04-02 17:25 UTC
Update the app icon with the attached. Should be all sizes required for iOS in the zip, but give me a shout if something's missing!

![Icon](https://user-images.githubusercontent.com/31798959/78280783-8c7b3500-7511-11ea-8ae6-5148fa66e009.png)

[app icons.zip](https://github.com/PlasticPatrol/PlasticPatrolWeb/files/4422537/app.icons.zip)

**Comment by neilfulwiler** [comment] 2020-04-20 19:05
ok i'm not very knowledgeable here, these might be naive questions/issues, but I'm seeing:

1) new icon.png is 1024x1024, old icon.png was 57x57 and there was an explicit 1024.png icon
2) and then here's the diff between old and new that I'm seeing
```
<
< 20              # ie new folder has 20pt icon, old one didnt
< 20@2x
< 20@3x
< 29
< 29@2x
< 29@3x
---
> Store
> 1024         # old icons had 1024 icon explicitly, can I just use icon.png?
12c7,9
< 40@3x
---
> 50.           # missing in new icons
> 50@2x
> 60
14a12,13
> 72            # missing in new icons
> 72@2x
17a17,21
> small                # missing in new icons
> small@2x
> small@3x
>
> @2x
```

**Comment by joe-mcguinness** [comment] 2020-04-22 17:35
The missing ones don't seem to be needed any more: https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/.

I think we can just use that 1024 icon I attached originally.

**Comment by neilfulwiler** [comment] 2020-04-26 16:27
ok this doesn't make much sense to me, but there are images in www/custom/images/logo-X.png that also seem to impact the icon. There's a 144, 152, and 192. 152 I can get from 76x2, could we get a 144 and 192 as well just to keep the same functonality?

**Comment by joe-mcguinness** [comment] 2020-04-27 17:57
![Icon_192](https://user-images.githubusercontent.com/31798959/80404314-ebd22800-88b8-11ea-9669-46c3d6c7891f.png)

![icon_144](https://user-images.githubusercontent.com/31798959/80404316-ed035500-88b8-11ea-8b8c-b0f9a9dbd898.png)

Attached both sizes

**Comment by neilfulwiler** [comment] 2020-05-22 20:19
ok this is done for iOS, leaving the issue open as its not done for android yet

**Comment by munroTom** [comment] 2020-07-25 10:29
Looks like there was a duplicate of this with some assets here https://github.com/PlasticPatrol/PlasticPatrolWeb/issues/131

**Closed** 2020-07-25 10:30 UTC
